# Generated by Django 5.1.4 on 2026-05-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('ai_strategy', models.CharField(default='random', max_length=30, verbose_name='Стратегия ИИ')),
                ('player_shots', models.IntegerField(default=0, verbose_name='Выстрелов игрока')),
                ('ai_shots', models.IntegerField(default=0, verbose_name='Выстрелов ИИ')),
                ('player_hits', models.IntegerField(default=0, verbose_name='Попаданий игрока')),
                ('ai_hits', models.IntegerField(default=0, verbose_name='Попаданий ИИ')),
                ('winner', models.CharField(blank=True, choices=[('player', 'Игрок'), ('ai', 'Компьютер')], max_length=10, verbose_name='Победитель')),
                ('questions_answered', models.IntegerField(default=0, verbose_name='Вопросов отвечено')),
                ('questions_correct', models.IntegerField(default=0, verbose_name='Правильных ответов')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория вопроса',
                'verbose_name_plural': 'Категории вопросов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('placement', 'Расстановка кораблей'), ('battle', 'Процесс боя'), ('strategy', 'Смена стратегии'), ('postmortem', 'Финал и анализ'), ('general', 'Общий')], default='general', max_length=20, verbose_name='Фаза игры')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Фрагмент кода')),
                ('option_a', models.CharField(max_length=500, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Вариант D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(verbose_name='Объяснение правильного ответа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.questioncategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
